### ISSUE TITLE
docker-compose fails with Error loading shared library libexpat.so.1

### ISSUE THREAD

**Issue by FlorianLudwig** [wagtail/bakerydemo#236]
```
$ docker-compose up --build -d
$ docker logs bakerydemo_app_1
[...]
/venv/lib/python3.5/site-packages/dotenv.py:56: UserWarning: Not reading .env - it doesn't exist.
  warnings.warn("Not reading {0} - it doesn't exist.".format(dotenv))
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/lib/python3.5/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/lib/python3.5/site-packages/django/core/management/base.py", line 350, in execute
    self.check()
  File "/venv/lib/python3.5/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/venv/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 60, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/venv/lib/python3.5/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/venv/lib/python3.5/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/venv/lib/python3.5/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/venv/lib/python3.5/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/venv/lib/python3.5/site-packages/django/urls/resolvers.py", line 396, in check
    for pattern in self.url_patterns:
  File "/venv/lib/python3.5/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/venv/lib/python3.5/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/venv/lib/python3.5/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/venv/lib/python3.5/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/code/bakerydemo/urls.py", line 5, in <module>
    from wagtail.admin import urls as wagtailadmin_urls
  File "/venv/lib/python3.5/site-packages/wagtail/admin/urls/__init__.py", line 13, in <module>
    from wagtail.admin.api import urls as api_urls
  File "/venv/lib/python3.5/site-packages/wagtail/admin/api/urls.py", line 11, in <module>
    for fn in hooks.get_hooks('construct_admin_api'):
  File "/venv/lib/python3.5/site-packages/wagtail/core/hooks.py", line 47, in get_hooks
    search_for_hooks()
  File "/venv/lib/python3.5/site-packages/wagtail/core/hooks.py", line 41, in search_for_hooks
    list(get_app_submodules('wagtail_hooks'))
  File "/venv/lib/python3.5/site-packages/wagtail/utils/apps.py", line 23, in get_app_submodules
    yield name, import_module('%s.%s' % (name, submodule_name))
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/venv/lib/python3.5/site-packages/wagtailfontawesome/wagtail_hooks.py", line 2, in <module>
    from pkg_resources import parse_version
  File "/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 35, in <module>
    import plistlib
  File "/usr/local/lib/python3.5/plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
  File "/usr/local/lib/python3.5/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: Error loading shared library libexpat.so.1: No such file or directory (needed by /usr/local/lib/python3.5/lib-dynload/pyexpat.cpython-35m-x86_64-linux-gnu.so)

```

**Comment by gasman** [comment]
Hi @FlorianLudwig - thanks for the report. This was reported earlier in #234 and is hopefully fixed in #235.
