### ISSUE TITLE
Relation "wagtailredirects_redirect" doesn't exist when loading initial data

### ISSUE THREAD

**Issue by Baschdl** [wagtail/bakerydemo#269]
`docker-compose run app /venv/bin/python manage.py load_initial_data` fails with
```
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "wagtailredirects_redirect" does not exist
LINE 1: DELETE FROM "wagtailredirects_redirect" WHERE "wagtailredire...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/code/bakerydemo/base/management/commands/load_initial_data.py", line 37, in handle
    Site.objects.get(hostname='localhost').delete()
  File "/venv/lib/python3.7/site-packages/django/db/models/base.py", line 938, in delete
    return collector.delete()
  File "/venv/lib/python3.7/site-packages/django/db/models/deletion.py", line 314, in delete
    count = qs._raw_delete(using=self.using)
  File "/venv/lib/python3.7/site-packages/django/db/models/query.py", line 736, in _raw_delete
    return sql.DeleteQuery(self.model).delete_qs(self, using)
  File "/venv/lib/python3.7/site-packages/django/db/models/sql/subqueries.py", line 75, in delete_qs
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1152, in execute_sql
    cursor.execute(sql, params)
  File "/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/venv/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "wagtailredirects_redirect" does not exist
LINE 1: DELETE FROM "wagtailredirects_redirect" WHERE "wagtailredire...
```

**Comment by gasman** [comment]
I'm unable to replicate this on a fresh bakerydemo install following the steps in the readme. This error would indicate that either migrations failed during the `docker-compose up --build -d` step, or the database was cleared after that step. One setup where the latter might possibly happen is a site on Heroku (which uses a non-permanent filesystem) with a sqlite database - however, without more details on the setup leading up to this error, it's not possible to troubleshoot further.
