### ISSUE TITLE
Error on workflows index under Postgres on a fully migrated Wagtail 6.2 instance

### ISSUE THREAD

**Issue by gasman** [wagtail/bakerydemo#501]
## Description

Running `./manage.py makemigrations` under Wagtail 6.2 generates a migration file `bakerydemo/base/migrations/0021_alter_footertext_locale.py` which is currently absent from the repo. If a fresh database is brought up under Postgres (via `./manage.py migrate ; ./manage.py load_initial_data`) with this migration in place, visiting the Workflows index page throws a SQL error.

## Steps to reproduce

Follow the [setup with virtualenv](https://github.com/wagtail/bakerydemo/?tab=readme-ov-file#setup-with-virtualenv) instructions, but before running the `./manage.py migrate` step, edit `bakerydemo/settings/local.py` to contain:

```python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'bakerydemo3',
    }
}
```
and then run:
```sh
createdb bakerydemo3
pip install psycopg2
./manage.py makemigrations
```
Then continue with the rest of the instructions, starting from `./manage.py migrate`.

Log in to the admin with `admin` / `changeme`, then go to Settings -> Workflows. This will raise the error:

<details>

<summary>ProgrammingError at /admin/workflows/list/ - more than one row returned by a subquery used as an expression</summary>

```
Traceback (most recent call last):
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The above exception (more than one row returned by a subquery used as an expression
) was the direct cause of the following exception:
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/wagtail/admin/auth.py", line 170, in overridden_render
    return render()
           ^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/template/defaulttags.py", line 325, in render
    if match:
       ^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/db/models/query.py", line 414, in __bool__
    self._fetch_all()
    ^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/hmmworkflows2/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: ProgrammingError at /admin/workflows/list/
Exception Value: more than one row returned by a subquery used as an expression

```

</details>

Removing the new migration and rebuilding the database, by running
```
rm bakerydemo/base/migrations/0021_alter_footertext_locale.py
dropdb bakerydemo3
createdb bakerydemo3
```
then `./manage.py migrate ; ./manage.py load_initial_data` as before, causes the error to disappear.

**Comment by gasman** [comment]
The failing SQL query is (reformatted for clarity):
```sql
SELECT
    "wagtailcore_workflow"."id",
    "wagtailcore_workflow"."name",
    "wagtailcore_workflow"."active",
    COUNT(
        (
            SELECT
                U0."content_type_id"
            FROM
                "wagtailcore_workflowcontenttype" U0
            WHERE
                U0."workflow_id" = ("wagtailcore_workflow"."id")
        )
    ) AS "content_types"
FROM
    "wagtailcore_workflow"
WHERE
    "wagtailcore_workflow"."active"
GROUP BY
    "wagtailcore_workflow"."id"
ORDER BY
    "wagtailcore_workflow"."name" ASC
LIMIT 1
```

Running the inner query in isolation:
```sql
SELECT
    U0."content_type_id"
FROM
    "wagtailcore_workflowcontenttype" U0
WHERE
    U0."workflow_id" = 1
```
returns the IDs 26 and 4 (corresponding to the base.Person and wagtailcore.Site content types) on a broken instance, and the ID 4 (corresponding to base.Person) on a working one. I suspect the `load_initial_data` fixture contains a hard-coded ID 4 to refer to the Person content type, and the presence of the new migration disrupts the order in which content types are allocated so that this is no longer correct. As a result, the `wagtailcore_workflowcontenttype` record in the fixture is supposed to match (and thus overwrite) the entry that was already created in migrations, but it doesn't, and ends up creating a second entry instead.

**Comment by gasman** [comment]
[The offending fixture record](https://github.com/wagtail/bakerydemo/blob/d0293edc0983d98d406e879df15edb13e44d3456/bakerydemo/base/fixtures/bakerydemo.json#L1519-L1525) was added here: https://github.com/wagtail/bakerydemo/pull/419#pullrequestreview-1491108623

It slipped through the normal practice of using natural keys for content types, because [the `content_type` field is also the primary key](https://github.com/wagtail/wagtail/blob/df08f999453dc02a674bec93937a38cacc4e4d79/wagtail/models/__init__.py#L3438-L3445). In any case, since [this record is created in a migration](https://github.com/wagtail/bakerydemo/blob/main/bakerydemo/base/migrations/0014_person_enable_default_workflow.py), I think it can be removed from the fixture.
